package data.userdata;

import java.util.ArrayList;
import javafx.scene.image.ImageView;
import po.userpo.UserPO;
import dataenum.findtype.FindUserType;
import dataenum.UserRole;
import dataenum.ResultMessage;
import org.junit.*;
import static org.junit.Assert.*;

/**
 * The class <code>UserDataTest</code> contains tests for the class
 * <code>{@link UserData}</code>.
 *
 * @generatedBy CodePro at 18-1-12 下午9:27
 * @author asus
 * @version $Revision: 1.0 $
 */
public class UserDataTest {
	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testDelete_1() throws Exception {
		UserData fixture = new UserData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.delete(UserData.java:77)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testDelete_2() throws Exception {
		UserData fixture = new UserData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.delete(UserData.java:77)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testDelete_3() throws Exception {
		UserData fixture = new UserData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.delete(UserData.java:77)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testDelete_4() throws Exception {
		UserData fixture = new UserData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.delete(UserData.java:77)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testDelete_5() throws Exception {
		UserData fixture = new UserData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.delete(UserData.java:77)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testDelete_6() throws Exception {
		UserData fixture = new UserData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.delete(UserData.java:77)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_1() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_2() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_3() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_4() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_5() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_6() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_7() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_8() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_9() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_10() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_11() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_12() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_13() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_14() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_15() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> find(String,FindUserType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testFind_16() throws Exception {
		UserData fixture = new UserData();
		String keyword = "";
		FindUserType type = FindUserType.ID;

		ArrayList<UserPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.find(UserData.java:96)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_1() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_2() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_3() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_4() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_5() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_6() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_7() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_8() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_9() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_10() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_11() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_12() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_13() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_14() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testInsert_15() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		assertNotNull(result);
	}

	/**
	 * Run the void main(String[]) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testMain_1() throws Exception {
		String[] args = new String[] {};

		UserData.main(args);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		// at data.userdata.UserData.main(UserData.java:32)
	}

	/**
	 * Run the void main(String[]) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testMain_2() throws Exception {
		String[] args = new String[] {};

		UserData.main(args);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.insert(UserData.java:43)
		// at data.userdata.UserData.main(UserData.java:32)
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_1() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_2() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_3() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_4() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_5() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_6() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_7() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_8() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_9() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_10() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_11() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_12() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_13() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_14() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<UserPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testShow_15() throws Exception {
		UserData fixture = new UserData();

		ArrayList<UserPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.show(UserData.java:157)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testUpdate_1() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.update(UserData.java:139)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testUpdate_2() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.update(UserData.java:139)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testUpdate_3() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.update(UserData.java:139)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testUpdate_4() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.update(UserData.java:139)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testUpdate_5() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.update(UserData.java:139)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testUpdate_6() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.update(UserData.java:139)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(UserPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Test
	public void testUpdate_7() throws Exception {
		UserData fixture = new UserData();
		UserPO po = new UserPO("", "", "", UserRole.FINANCIAL_MANAGER, new ImageView());

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.userdata.UserData.update(UserData.java:139)
		assertNotNull(result);
	}

	/**
	 * Perform pre-test initialization.
	 *
	 * @throws Exception
	 *             if the initialization fails for some reason
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@Before
	public void setUp() throws Exception {
		// add additional set up code here
	}

	/**
	 * Perform post-test clean-up.
	 *
	 * @throws Exception
	 *             if the clean-up fails for some reason
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	@After
	public void tearDown() throws Exception {
		// Add additional tear down code here
	}

	/**
	 * Launch the test.
	 *
	 * @param args
	 *            the command line arguments
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:27
	 */
	public static void main(String[] args) {
		new org.junit.runner.JUnitCore().run(UserDataTest.class);
	}
}